use anyhow::Result;
use libbpf_rs::OpenObject;
use libbpf_rs::skel::{OpenSkel, Skel, SkelBuilder};
use std::mem::MaybeUninit;

// Include the skeleton generated by libbpf-cargo in build.rs
mod guard {
    include!(concat!(env!("OUT_DIR"), "/guard.skel.rs"));
}

use guard::*;

fn main() -> Result<()> {
    // 1. Instantiate the builder
    let skel_builder = GuardSkelBuilder::default();

    // 2. Allocate an uninitialized buffer for the underlying C bpf_object
    let mut open_object = MaybeUninit::uninit();

    // 3. Open the BPF object (reads ELF sections and prepares maps)
    let open_skel = skel_builder.open(&mut open_object)?;

    // 4. Load the bytecode into the kernel (runs the verifier)
    let mut skel = open_skel.load()?;

    println!("libbpf-rs skeleton successfully loaded into kernel!");

    Ok(())
}
