use anyhow::{Context, Result, bail};
use clap::Parser;
use libbpf_rs::MapCore;
use libbpf_rs::OpenObject;
use libbpf_rs::skel::{OpenSkel, Skel, SkelBuilder};
use std::mem::MaybeUninit;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::thread;
use std::time::Duration;

// Include the skeleton generated by libbpf-cargo in build.rs
mod guard {
    include!(concat!(env!("OUT_DIR"), "/guard.skel.rs"));
}

use guard::*;

#[derive(Debug, Parser)]
#[command(name = "xdp-ai-guard", about = "eBPF AI Guard and Research Engine")]
struct Args {
    /// Network interface to attach to
    #[arg(short, long, default_value = "lo")]
    iface: String,

    /// Polling interval in milliseconds
    #[arg(short, long, default_value = "1000")]
    poll_interval: u64,
}

//Convert network interface name to index
fn get_ifindex(iface_name: &str) -> Result<i32> {
    let iface_cstr = std::ffi::CString::new(iface_name)?;
    let ifindex = unsafe { libc::if_nametoindex(iface_cstr.as_ptr()) };
    if ifindex == 0 {
        bail!("Failed to get ifindex for interface: {}", iface_name);
    }
    Ok(ifindex as i32)
}

fn main() -> Result<()> {
    let args = Args::parse();
    let ifindex = get_ifindex(&args.iface)?;
    println!(
        "[*] Selected interface: {} (ifindex: {})",
        args.iface, ifindex
    );

    // 1. Instantiate the builder
    let skel_builder = GuardSkelBuilder::default();

    // 2. Allocate an uninitialized buffer for the underlying C bpf_object
    let mut open_object = MaybeUninit::uninit();

    // 3. Open the BPF object (reads ELF sections and prepares maps)
    let open_skel = skel_builder
        .open(&mut open_object)
        .context("Failed to open BPF object")?;

    // 4. Load the bytecode into the kernel (runs the verifier)
    let mut skel = open_skel
        .load()
        .context("Kernel verifier rejected BPF program")?;
    println!("[+] BPF program successfully verified and loaded into kernel.");

    // 5. Attach the BPF program to the network interface
    // Flags: XDP_FLAGS_UPDATE_IF_NOEXIST | XDP_FLAGS_SKB_MODE
    let _link = skel
        .progs
        .xdp_guard_func
        .attach_xdp(ifindex)
        .context(format!("Failed to attach XDP to interface {}", args.iface))?;

    // 6. Setup graceful signal handler
    let running = Arc::new(AtomicBool::new(true));
    let r = running.clone();
    ctrlc::set_handler(move || {
        println!("\n[*] Detaching and shutting down...");
        r.store(false, Ordering::SeqCst);
    })?;

    // 7. Polling loop for statistics
    let stats_map = skel.maps.stats_map;
    let num_cpus = libbpf_rs::num_possible_cpus().unwrap_or(1);

    println!("[*] Monitoring traffic... Press Ctrl+C to stop.\n");
    println!("{:>12} | {:>12}", "PASS PKTS", "DROP PKTS");
    println!("-----------------------------");

    while running.load(Ordering::SeqCst) {
        //Read Per CPU array values
        let pass_key = 0u32.to_ne_bytes();
        let drop_key = 1u32.to_ne_bytes();
        let pass_count = read_percpu_sum(&stats_map, &pass_key, num_cpus);
        let drop_count = read_percpu_sum(&stats_map, &drop_key, num_cpus);

        print!("\r{:>12} | {:>12}", pass_count, drop_count);
        use std::io::Write;
        let _ = std::io::stdout().flush();

        thread::sleep(Duration::from_millis(args.poll_interval));
    }

    println!("\n[+] Done. Clean exit.");
    Ok(())
}

fn read_percpu_sum(map: &libbpf_rs::Map, key: &[u8], num_cpus: usize) -> u64 {
    match map.lookup_percpu(key, libbpf_rs::MapFlags::empty()) {
        Ok(Some(raw_percpu_bytes)) => {
            // raw_percpu_bytes is a Vec<Vec<u8>>, one per CPU
            raw_percpu_bytes
                .iter()
                .filter_map(|cpu_slice| {
                    if cpu_slice.len() >= 8 {
                        Some(u64::from_ne_bytes(cpu_slice[0..8].try_into().unwrap()))
                    } else {
                        None
                    }
                })
                .sum()
        }
        _ => 0,
    }
}
