use std::io::stdout;
use std::mem::MaybeUninit;
use std::time::{Duration, SystemTime};

use anyhow::{Context, Result, bail};
use clap::Parser;
use crossterm::{
    event::{self, Event, KeyCode, KeyEventKind},
    execute,
    terminal::{EnterAlternateScreen, LeaveAlternateScreen, disable_raw_mode, enable_raw_mode},
};
use libbpf_rs::MapCore;
use libbpf_rs::OpenObject;
use libbpf_rs::skel::{OpenSkel, Skel, SkelBuilder};
use ratatui::Terminal;
use ratatui::backend::CrosstermBackend;

use xdp_ai_guard::ui::app::{App, Tab};

// Include the skeleton generated by libbpf-cargo during cargo build
mod guard {
    include!(concat!(env!("OUT_DIR"), "/guard.skel.rs"));
}
use guard::*;

#[derive(Parser, Debug)]
#[command(
    name = "xdp-ai-guard",
    about = "High-speed AI Inference Guard & eBPF Research Harness"
)]
struct Args {
    /// Network interface to bind the XDP guard to (e.g., eth0, lo)
    #[arg(short, long, default_value = "lo")]
    iface: String,

    /// Run in mock/simulation mode without loading kernel eBPF (no sudo required)
    #[arg(long, default_value_t = false)]
    mock: bool,
}

fn get_ifindex(iface_name: &str) -> Result<i32> {
    let iface_cstr = std::ffi::CString::new(iface_name)?;
    let ifindex = unsafe { libc::if_nametoindex(iface_cstr.as_ptr()) };
    if ifindex == 0 {
        bail!("Network interface '{}' not found", iface_name);
    }
    Ok(ifindex as i32)
}

fn main() -> Result<()> {
    let args = Args::parse();

    // 1. Initialize Terminal in Raw Mode & Alternate Screen
    enable_raw_mode()?;
    let mut stdout = stdout();
    execute!(stdout, EnterAlternateScreen)?;
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;

    let mut app = App::new(args.iface.clone());

    // 2. Dispatch execution: Mock Mode vs. Live Kernel Attachment
    let loop_res = if args.mock {
        run_mock_loop(&mut terminal, &mut app)
    } else {
        run_ebpf_loop(&mut terminal, &mut app, &args.iface)
    };

    // 3. Clean Terminal Teardown (ensure cursor and terminal state are restored)
    disable_raw_mode()?;
    execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
    terminal.show_cursor()?;

    loop_res
}

fn run_ebpf_loop<B: ratatui::backend::Backend>(
    terminal: &mut Terminal<B>,
    app: &mut App,
    iface: &str,
) -> Result<()> {
    let ifindex = get_ifindex(iface)?;

    // Instantiate and open the BPF skeleton
    let skel_builder = GuardSkelBuilder::default();
    let mut open_object = MaybeUninit::uninit();
    let open_skel = skel_builder
        .open(&mut open_object)
        .context("Failed to open BPF object (make sure you run with sudo)")?;

    // Load program into kernel (verifier runs here)
    let mut skel = open_skel
        .load()
        .context("Kernel verifier rejected BPF program")?;

    // Attach to XDP hook on the specified interface
    let _link = skel
        .progs
        .xdp_guard_func
        .attach_xdp(ifindex)
        .context(format!("Failed to attach XDP to interface {}", iface))?;

    let num_cpus = libbpf_rs::num_possible_cpus().unwrap_or(1);
    let stats_map = skel.maps.stats_map;
    let tick_rate = Duration::from_millis(50);

    let pass_key = 0u32.to_ne_bytes();
    let drop_key = 1u32.to_ne_bytes();

    loop {
        // Read live per-CPU packet counters
        let pass_sum = read_percpu_sum(&stats_map, &pass_key, num_cpus);
        let drop_sum = read_percpu_sum(&stats_map, &drop_key, num_cpus);
        app.metrics.update(pass_sum, drop_sum);

        terminal.draw(|f| app.render(f))?;

        if event::poll(tick_rate)? {
            if let Event::Key(key) = event::read()? {
                // Ignore key releases to prevent double actions
                if key.kind == KeyEventKind::Press && handle_input(app, key.code) {
                    break;
                }
            }
        }
    }

    Ok(())
}

fn run_mock_loop<B: ratatui::backend::Backend>(
    terminal: &mut Terminal<B>,
    app: &mut App,
) -> Result<()> {
    let tick_rate = Duration::from_millis(50);
    let mut mock_pass = 1000u64;
    let mut mock_drop = 15u64;

    loop {
        // Synthesize network fluctuation for testing UI dynamics
        let nanos = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .subsec_nanos() as u64;
        let delta = (nanos % 120) + 10;
        mock_pass += delta;
        if delta % 8 == 0 {
            mock_drop += 1;
        }

        app.metrics.update(mock_pass, mock_drop);

        terminal.draw(|f| app.render(f))?;

        if event::poll(tick_rate)? {
            if let Event::Key(key) = event::read()? {
                if key.kind == KeyEventKind::Press && handle_input(app, key.code) {
                    break;
                }
            }
        }
    }

    Ok(())
}

fn handle_input(app: &mut App, key: KeyCode) -> bool {
    match key {
        // Quit
        KeyCode::Char('q') | KeyCode::Char('Q') => true,

        // Tab Navigation
        KeyCode::Tab => {
            app.next_tab();
            false
        }
        KeyCode::BackTab => {
            app.prev_tab();
            false
        }
        KeyCode::Char('1') => {
            app.current_tab = Tab::Guard;
            false
        }
        KeyCode::Char('2') => {
            app.current_tab = Tab::VerifierResearch;
            false
        }
        KeyCode::Char('3') => {
            app.current_tab = Tab::SyscallBenchmark;
            false
        }

        // Verifier Lab Navigation & Execution
        KeyCode::Down | KeyCode::Char('j') => {
            app.next_verifier_test();
            false
        }
        KeyCode::Up | KeyCode::Char('k') => {
            app.prev_verifier_test();
            false
        }
        KeyCode::Char('r') | KeyCode::Char('R') => {
            app.execute_selected_audit();
            false
        }

        // Trigger Live Hardware Micro-Benchmark
        KeyCode::Char('b') | KeyCode::Char('B') => {
            app.run_hardware_benchmark();
            false
        }

        _ => false,
    }
}

fn read_percpu_sum(map: &libbpf_rs::Map, key: &[u8], _num_cpus: usize) -> u64 {
    match map.lookup_percpu(key, libbpf_rs::MapFlags::empty()) {
        Ok(Some(raw_percpu_bytes)) => raw_percpu_bytes
            .iter()
            .filter_map(|cpu_slice| {
                if cpu_slice.len() >= 8 {
                    Some(u64::from_ne_bytes(cpu_slice[0..8].try_into().unwrap()))
                } else {
                    None
                }
            })
            .sum(),
        _ => 0,
    }
}
